{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eee700d3-7f87-4ab6-8ff6-8b332ace90d6",
   "metadata": {},
   "outputs": [],
   "source": [
    "## Instalaciones si no se tiene\n",
    "!pip install sqlalchemy[mysql]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "4801f141-3c31-4915-8216-648b7f423279",
   "metadata": {},
   "outputs": [],
   "source": [
    "import great_expectations as gx\n",
    "import great_expectations.expectations as gxe\n",
    "from great_expectations.checkpoint import UpdateDataDocsAction\n",
    "\n",
    "context = gx.get_context(mode=\"file\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "68240055-693f-4906-924f-8bdb0b743345",
   "metadata": {},
   "outputs": [],
   "source": [
    "## Connect to your data\n",
    "\n",
    "PG_CONNECTION_STRING = \"postgresql+psycopg2://postgres:postgres@database/postgres\"\n",
    "pg_datasource = context.data_sources.add_postgres(name=\"pg_datasource\", connection_string=PG_CONNECTION_STRING)\n",
    "asset = pg_datasource.add_table_asset(name=\"pedidos_data\", table_name=\"clientes\")\n",
    "bd = asset.add_batch_definition_whole_table(\"BD\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "c9273a76-4118-46d2-91c5-181a1bb75048",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "ExpectColumnValuesToBeUnique(id='52c998ad-f311-4f8b-a64c-b01ed58ec1d2', meta=None, notes=None, result_format=<ResultFormat.BASIC: 'BASIC'>, description=None, catch_exceptions=True, rendered_content=None, batch_id=None, row_condition=None, condition_parser=None, column='dni', mostly=1.0)"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "## Create Expectations\n",
    "suite = context.suites.add(gx.ExpectationSuite(\"Suite\"))\n",
    "vd = gx.ValidationDefinition(\n",
    "    name=\"Validation Definition\",\n",
    "    data=bd,\n",
    "    suite=suite\n",
    ")\n",
    "\n",
    "context.validation_definitions.add(vd)\n",
    "\n",
    "## Completitud\n",
    "suite.add_expectation(gxe.ExpectColumnValuesToNotBeNull(column=\"id_cliente\"))\n",
    "suite.add_expectation(gxe.ExpectColumnValuesToNotBeNull(column=\"nombre\"))\n",
    "suite.add_expectation(gxe.ExpectColumnValuesToNotBeNull(column=\"email\"))\n",
    "suite.add_expectation(gxe.ExpectColumnValuesToNotBeNull(column=\"telefono\"))\n",
    "\n",
    "## Precision semantica\n",
    "suite.add_expectation(gxe.ExpectColumnValuesToMatchLikePattern(\n",
    "    column=\"telefono\",\n",
    "    like_pattern=r\"^\\d{4}-\\d{4}$\"\n",
    "))\n",
    "\n",
    "## Violacion de dominio\n",
    "suite.add_expectation(gxe.ExpectColumnValuesToBeBetween(\n",
    "    column=\"numero_secuencia\",\n",
    "    min_value=1,\n",
    "    max_value= None,\n",
    "    strict_min=True,\n",
    "    strict_max=False\n",
    "))\n",
    "\n",
    "## Violacion de restricciones\n",
    "suite.add_expectation(gxe.ExpectColumnValuesToBeBetween(\n",
    "    column=\"numero_secuencia\",\n",
    "    min_value=1,\n",
    "    max_value= None,\n",
    "    strict_min=True,\n",
    "    strict_max=False\n",
    "))\n",
    "\n",
    "\n",
    "## Violacion valor unico\n",
    "suite.add_expectation(gxe.ExpectColumnValuesToBeUnique(\n",
    "    column=\"dni\"))\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "8cf5cbce-e949-477b-915b-7e617cdf9a5b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "ExpectColumnPairValuesToBeInSet(id='b73f03fc-c7fc-49cc-aa78-b208ff82fdc0', meta=None, notes=None, result_format=<ResultFormat.BASIC: 'BASIC'>, description=None, catch_exceptions=True, rendered_content=None, batch_id=None, row_condition=None, condition_parser=None, column_A='cp', column_B='poblacion', mostly=1.0, value_pairs_set=[('28001', 'Cuenca'), ('28002', 'Valencia')], ignore_row_if='both_values_are_missing')"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from sqlalchemy import create_engine\n",
    "import pandas as pd\n",
    "\n",
    "engine = create_engine(PG_CONNECTION_STRING)\n",
    "\n",
    "## Violacion integridad referencial\n",
    "query = \"\"\"SELECT cp, poblacion \n",
    "FROM clientes\n",
    "GROUP BY cp, poblacion\n",
    "HAVING COUNT(DISTINCT poblacion) = 1\"\"\"\n",
    "\n",
    "valid_pairs = pd.read_sql(query,engine)\n",
    "\n",
    "valid_pairs = valid_pairs.drop_duplicates(subset=['cp'], keep='first')\n",
    "\n",
    "valid_list = list(valid_pairs.itertuples(index = False, name = None))\n",
    "\n",
    "suite.add_expectation(gxe.ExpectColumnPairValuesToBeInSet(\n",
    "    column_A=\"cp\",\n",
    "    column_B=\"poblacion\",\n",
    "    value_pairs_set= valid_list,\n",
    "    mostly=1.0\n",
    "))\n",
    "    \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "93d84ad1-452a-497c-a971-656322fb16e9",
   "metadata": {},
   "outputs": [
    {
     "ename": "DataContextError",
     "evalue": "Cannot add Checkpoint with name Checkpoint because it already exists.",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mDataContextError\u001b[39m                          Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[6]\u001b[39m\u001b[32m, line 2\u001b[39m\n\u001b[32m      1\u001b[39m \u001b[38;5;66;03m## Validate your data\u001b[39;00m\n\u001b[32m----> \u001b[39m\u001b[32m2\u001b[39m checkpoint = \u001b[43mcontext\u001b[49m\u001b[43m.\u001b[49m\u001b[43mcheckpoints\u001b[49m\u001b[43m.\u001b[49m\u001b[43madd\u001b[49m\u001b[43m(\u001b[49m\u001b[43mgx\u001b[49m\u001b[43m.\u001b[49m\u001b[43mCheckpoint\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m      3\u001b[39m \u001b[43m    \u001b[49m\u001b[43mname\u001b[49m\u001b[43m=\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mCheckpoint\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[32m      4\u001b[39m \u001b[43m    \u001b[49m\u001b[43mvalidation_definitions\u001b[49m\u001b[43m=\u001b[49m\u001b[43m[\u001b[49m\u001b[43mvd\u001b[49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m      5\u001b[39m \u001b[43m    \u001b[49m\u001b[43mactions\u001b[49m\u001b[43m=\u001b[49m\u001b[43m[\u001b[49m\n\u001b[32m      6\u001b[39m \u001b[43m        \u001b[49m\u001b[43mUpdateDataDocsAction\u001b[49m\u001b[43m(\u001b[49m\u001b[43mname\u001b[49m\u001b[43m=\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mupdate_data_docs\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[32m      7\u001b[39m \u001b[43m    \u001b[49m\u001b[43m]\u001b[49m\n\u001b[32m      8\u001b[39m \u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m     10\u001b[39m checkpoint_result = checkpoint.run()\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/local/lib/python3.11/site-packages/great_expectations/core/factory/checkpoint_factory.py:41\u001b[39m, in \u001b[36mCheckpointFactory.add\u001b[39m\u001b[34m(self, checkpoint)\u001b[39m\n\u001b[32m     39\u001b[39m key = \u001b[38;5;28mself\u001b[39m._store.get_key(name=checkpoint.name, \u001b[38;5;28mid\u001b[39m=\u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[32m     40\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m._store.has_key(key=key):\n\u001b[32m---> \u001b[39m\u001b[32m41\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m DataContextError(  \u001b[38;5;66;03m# noqa: TRY003\u001b[39;00m\n\u001b[32m     42\u001b[39m         \u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33mCannot add Checkpoint with name \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mcheckpoint.name\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m because it already exists.\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m     43\u001b[39m     )\n\u001b[32m     45\u001b[39m \u001b[38;5;28mself\u001b[39m._store.add(key=key, value=checkpoint)\n\u001b[32m     47\u001b[39m \u001b[38;5;66;03m# TODO: Add id adding logic to CheckpointStore to prevent round trip\u001b[39;00m\n",
      "\u001b[31mDataContextError\u001b[39m: Cannot add Checkpoint with name Checkpoint because it already exists."
     ]
    }
   ],
   "source": [
    "## Validate your data\n",
    "checkpoint = context.checkpoints.add(gx.Checkpoint(\n",
    "    name=\"Checkpoint\",\n",
    "    validation_definitions=[vd],\n",
    "    actions=[\n",
    "        UpdateDataDocsAction(name=\"update_data_docs\")\n",
    "    ]\n",
    "))\n",
    "\n",
    "checkpoint_result = checkpoint.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0b9c8d63-2ca3-4891-9349-78830eba54b5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
