[2025-03-06T10:20:28.803+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-06T10:20:28.823+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clientes_dag.gx_run_audit manual__2025-03-06T10:20:25.729301+00:00 [queued]>
[2025-03-06T10:20:28.829+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clientes_dag.gx_run_audit manual__2025-03-06T10:20:25.729301+00:00 [queued]>
[2025-03-06T10:20:28.830+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-03-06T10:20:28.839+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): gx_run_audit> on 2025-03-06 10:20:25.729301+00:00
[2025-03-06T10:20:28.845+0000] {standard_task_runner.py:63} INFO - Started process 410 to run task
[2025-03-06T10:20:28.847+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'clientes_dag', 'gx_run_audit', 'manual__2025-03-06T10:20:25.729301+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/clientes_dag.py', '--cfg-path', '/tmp/tmpd4cx5utf']
[2025-03-06T10:20:28.850+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask gx_run_audit
[2025-03-06T10:20:28.884+0000] {task_command.py:426} INFO - Running <TaskInstance: clientes_dag.gx_run_audit manual__2025-03-06T10:20:25.729301+00:00 [running]> on host a3d267d0ec58
[2025-03-06T10:20:29.174+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='clientes_dag' AIRFLOW_CTX_TASK_ID='gx_run_audit' AIRFLOW_CTX_EXECUTION_DATE='2025-03-06T10:20:25.729301+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-06T10:20:25.729301+00:00'
[2025-03-06T10:20:29.175+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-06T10:20:29.205+0000] {file_data_context.py:209} INFO - FileDataContext loading fluent config
[2025-03-06T10:20:29.207+0000] {config.py:191} INFO - Loading 'datasources' ->
[{'assets': [...],
  'connection_string': 'postgresql+psycopg2://postgres:postgres@database/postgres',
  'id': 'ec26aaf3-15f6-44c8-99b4-d5447be7db07',
  'name': 'pg_datasource',
  'type': 'postgres'}]
[2025-03-06T10:20:29.254+0000] {abstract_data_context.py:2416} INFO - Loaded 'pg_datasource' from fluent config
[2025-03-06T10:20:29.262+0000] {batch_filter.py:243} INFO - batch_slice: None was parsed to: slice(0, None, None)
[2025-03-06T10:20:29.264+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.264+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.265+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.266+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.266+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.267+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.267+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.276+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.276+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.277+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.277+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.278+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.278+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.279+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.287+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.288+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.288+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.289+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.289+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.290+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.290+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.299+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.299+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.300+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.300+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.301+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.301+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.301+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.327+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/28 [00:00<?, ?it/s]
[2025-03-06T10:20:29.327+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/28 [00:00<?, ?it/s]
[2025-03-06T10:20:29.337+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   7%|7         | 2/28 [00:00<00:00, 196.20it/s]
[2025-03-06T10:20:29.347+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   7%|7         | 2/28 [00:00<00:00, 101.71it/s]
[2025-03-06T10:20:29.350+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  14%|#4        | 4/28 [00:00<00:00, 177.22it/s]
[2025-03-06T10:20:29.358+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  14%|#4        | 4/28 [00:00<00:00, 129.42it/s]
[2025-03-06T10:20:29.360+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  29%|##8       | 8/28 [00:00<00:00, 244.30it/s]
[2025-03-06T10:20:29.367+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  29%|##8       | 8/28 [00:00<00:00, 199.81it/s]
[2025-03-06T10:20:29.377+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  86%|########5 | 24/28 [00:00<00:00, 483.20it/s]
[2025-03-06T10:20:29.381+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  86%|########5 | 24/28 [00:00<00:00, 444.33it/s]
[2025-03-06T10:20:29.385+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 28/28 [00:00<00:00, 481.86it/s]
[2025-03-06T10:20:29.388+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 28/28 [00:00<00:00, 456.39it/s]
[2025-03-06T10:20:29.389+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 28/28 [00:00<00:00, 453.99it/s]
[2025-03-06T10:20:29.389+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 28/28 [00:00<00:00, 451.42it/s]
[2025-03-06T10:20:29.395+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.395+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.396+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.397+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.397+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.398+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.398+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.399+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.399+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.400+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.400+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.401+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.401+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.402+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.402+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.403+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.404+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.405+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.407+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.408+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.408+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.409+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.409+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.410+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.411+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.412+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.412+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.413+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.413+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.414+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.414+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.415+0000] {expectation.py:1137} INFO - _get_default_value called with key "table", but it is not a known field
[2025-03-06T10:20:29.647+0000] {unix.py:142} WARNING - /etc/timezone is deprecated on Debian, and no longer reliable. Ignoring.
[2025-03-06T10:20:29.708+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-03-06T10:20:29.710+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-06T10:20:29.716+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=clientes_dag, task_id=gx_run_audit, execution_date=20250306T102025, start_date=20250306T102028, end_date=20250306T102029
[2025-03-06T10:20:29.764+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-06T10:20:29.776+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-06T10:20:29.778+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
